// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDElG_kx31HkfBmkPHnY_gLv1liMYyhwLg',
    appId: '1:147332287440:web:88e16f6109ea854df007d5',
    messagingSenderId: '147332287440',
    projectId: 'shakti-database-3593a',
    authDomain: 'shakti-database-3593a.firebaseapp.com',
    storageBucket: 'shakti-database-3593a.appspot.com',
    measurementId: 'G-Q165G40HDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD53DV91o-Tk1f5QPaF_PSsgeWa3AU19FU',
    appId: '1:147332287440:android:d5c1165ffbbda251f007d5',
    messagingSenderId: '147332287440',
    projectId: 'shakti-database-3593a',
    storageBucket: 'shakti-database-3593a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChzDYXWKdTXS6eCH3mwIniZwe-ZMjdmCM',
    appId: '1:147332287440:ios:30e575dc42da1e08f007d5',
    messagingSenderId: '147332287440',
    projectId: 'shakti-database-3593a',
    storageBucket: 'shakti-database-3593a.appspot.com',
    iosClientId: '147332287440-rtt048cbq2rvffnam151gfa1t57c69qd.apps.googleusercontent.com',
    iosBundleId: 'com.example.shakti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChzDYXWKdTXS6eCH3mwIniZwe-ZMjdmCM',
    appId: '1:147332287440:ios:30e575dc42da1e08f007d5',
    messagingSenderId: '147332287440',
    projectId: 'shakti-database-3593a',
    storageBucket: 'shakti-database-3593a.appspot.com',
    iosClientId: '147332287440-rtt048cbq2rvffnam151gfa1t57c69qd.apps.googleusercontent.com',
    iosBundleId: 'com.example.shakti',
  );
}
